### ISSUE TITLE
Using tiktoken

### ISSUE THREAD

**Issue by ScotterC** [ankane/tokenizers-ruby#12]
Hey thanks for writing up this gem! (and all the other ML ones).

This may be a naive question but can [tiktoken](https://github.com/openai/tiktoken) be invoked as a tokenizer?

**Comment by ankane** [comment]
tiktoken is another tokenization library (rather than a specific encoding/model). You can use either for GPT-2 tokenization (but looks like tiktoken supports [a few others](https://github.com/openai/openai-cookbook/blob/main/examples/How_to_count_tokens_with_tiktoken.ipynb) that aren't on the [Hugging Face hub](https://huggingface.co/models) yet).
